name: CI

on: 
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: pdm-project/setup-pdm@v3
      - name: Install dependencies
        run: pdm sync
      - name: Lint with black and isort
        run: pdm run lint-check

  publish:
    needs: lint
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: pdm-project/setup-pdm@v3
      - name: Install dependencies
        run: pdm sync
      - name: Publish
        run: pdm run publish
